### ISSUE TITLE
Update to imperva/terraform-provider-incapsula

### ISSUE THREAD

**Issue by jonDowdle** [terraform-providers/terraform-provider-incapsula#1]
The version of the provider at https://github.com/imperva/terraform-provider-incapsula has had various changes that aren't included in this (the official) version of the provider. One specific feature was added by @kireledan in https://github.com/imperva/terraform-provider-incapsula/pull/40.

How can we go about synchronizing this repo with the version in the Imperva org? If there's any steps we need to do, please let us know.

**Comment by anandkunal** [comment]
Hi @jonDowdle - based on a recent email that Hashicorp sent out, we're going ahead and transitioning from this Git repository back to the Imperva one (link you provided). The reason is that Hashi is asking us to move the provider to the Terraform Registry (https://registry.terraform.io/). This work is already underway on the Imperva side. In the mean time, I recommend you revert to the Imperva Git repository. If you're looking for specific builds, let me know - I'm happy to assist.

**Comment by jonDowdle** [comment]
@anandkunal Awesome. I believe we prefer the one I linked to (the one in the imperva org) so this is great news. Thanks for following up on this! If you need any help, feel free to ping me.

**Comment by kireledan** [comment]
Would you be able to redefine the go module to point to the imperva repo instead of this one? Since this repo won't be used as upstream it might cause a lot of confusion.

**Comment by anandkunal** [comment]
Makes sense @kireledan - I'll create a new issue to track the work in the Imperva repo.
